# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Artwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   # Pods for Artwork
   rn_path = '../node_modules/react-native'

   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
   pod 'React', path: rn_path, subspecs: [
     'Core',
     'RCTActionSheet',
     'RCTAnimation',
     'RCTGeolocation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTNetwork',
     'RCTSettings',
     'RCTText',
     'RCTVibration',
     'RCTWebSocket',
   ]

  # Pods for Artwork
  pod 'AccountKit'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'  
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'
  
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'
  pod 'AccountKit'
  pod 'Fabric', '~> 1.7.5'
  pod 'Crashlytics', '~> 3.10.4'
 # pod 'GoogleSignIn'
# pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  
  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-in-app-utils', :path => '../node_modules/react-native-in-app-utils'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
      
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
